[package]
name = "ritos"
version = "0.0.1"
authors = [""]
edition = "2018"

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"

[features]
default = ["cortex-a"]
bsp_rpi3 = []

[dependencies]
cortex-a = { version = "2.9.x", optional = true }