[package]
name = "ritos"
version = "0.0.1"
authors = [""]
edition = "2018"

[package.metadata.cargo-xbuild]
sysroot_path = ".xbuild_sysroot"

[dependencies]
cortex-a = "2.9.x"
register = "0.5.x"
spin = "0.5.2"
